# Generated by Django 5.1 on 2024-09-17 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_options_alter_customuser_username'),
        ('social_django', '0016_alter_usersocialauth_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='social_auth1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.usersocialauth'),
        ),
    ]
