# Generated by Django 5.1 on 2024-09-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_social_auth1_customuser_social_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='social_user',
        ),
    ]
